project:
  type: website
  output-dir: docs

website:
  title: "emmanueldogbey.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: projects.qmd
        text: Featured Projects
      - href: posts/
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



